# Generated by Django 3.2.13 on 2022-09-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_maker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='products_in_order',
            field=models.ManyToManyField(related_name='products_in_order', through='customer.OrderItem', to='products.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
