# Generated by Django 3.2.13 on 2022-09-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220920_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='aprroval_status',
            new_name='approval_status',
        ),
    ]
