# Generated by Django 3.2.13 on 2022-09-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_aprroval_status_orderitem_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='ordered_by_user',
        ),
    ]
