# Generated by Django 3.2.13 on 2022-09-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_user_orderitem_ordered_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='check_out_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
    ]
