# Generated by Django 3.2.13 on 2022-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220921_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='Total_payment_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Cart Total Amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Coupon Discount  Amount '),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Order Total Amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_quantity_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Order Cost'),
        ),
    ]
