# Generated by Django 3.2.13 on 2022-09-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='customer.OrderItem'),
        ),
    ]
