# Generated by Django 3.2.13 on 2022-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20220929_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order id'),
        ),
    ]
