# Generated by Django 3.2.13 on 2022-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_value_type'),
        ('customer', '0012_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='coupons_used', to='coupon.Coupon'),
        ),
    ]
