# Generated by Django 3.2.13 on 2022-10-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_orderitem_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coupons',
        ),
    ]
