# Generated by Django 3.2.13 on 2022-09-21 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(choices=[('category', 'Category'), ('product', 'Product'), ('all', 'All')], max_length=50)),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='rate')),
                ('coupon_id', models.CharField(blank=True, max_length=20, verbose_name='Coupon id')),
                ('coupon_status', models.BooleanField(default=False, max_length=100, verbose_name='Coupon status')),
                ('value_type', models.CharField(choices=[('Percentage', 'percentage'), ('cash', 'Cash')], default='percentage', max_length=255, verbose_name='Value Type ')),
                ('coupon_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_coupon', to='products.category')),
                ('coupon_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_user', to=settings.AUTH_USER_MODEL)),
                ('coupon_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_coupon', to='products.product')),
            ],
        ),
    ]
