# Generated by Django 3.2.13 on 2022-09-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_status',
            new_name='coupon_used_status',
        ),
    ]
