# Generated by Django 3.2.13 on 2022-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_coupon_status_coupon_coupon_used_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_used_status',
            field=models.BooleanField(default=False, max_length=100, verbose_name='Coupon used status'),
        ),
    ]
