# Generated by Django 3.2.13 on 2022-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_coupon_used_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('cash', 'Cash')], default='percentage', max_length=255, verbose_name='Value Type '),
        ),
    ]
