# Generated by Django 3.2.13 on 2022-09-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220930_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
