# Generated by Django 3.2.13 on 2022-10-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221005_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='colour', to='products.colour'),
        ),
    ]
